# server port
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.212:3306/my_database
    username: metanet
    password: Abcd1234!

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG

# jwt key
jwt:
  secret: dlrjsmsbfvmfhwprxmdmlwpdltmsxhzmsdkaghghkzldlqslekdkanehdlrjtdmfdkffurhgkwlaktlqtldh
#  expiration: 3600 # 토큰 만료 시간 (초 단위)